@@startuml 
left to right direction
skinparam HorizontalSpacing 100
skinparam actorStyle awesome
skinparam UsecaseBackgroundColor #lavender
skinparam UsecaseBorderColor #black
skinparam rectangle {
  Shadowing false
  BorderColor Black
}



rectangle "Gestão de Reserva de Hotel" {

    'Atores'
    actor Cliente
    actor Recepcionista
    actor Gerente 
    actor Sistema 
    actor Restaurante 

    'Casos de Uso do cliente'

    rectangle "Ações do cliente" as C {
        package "Processo de Reserva" as 1C {
            usecase "Acessa o site" as C1
            usecase "Realiza o cadastro" as C2 
            usecase "Seleciona uma data" as C3
            usecase "Realiza reserva" as C4
            usecase "Seleciona serviços adicionais" as C5
            usecase "Realiza pagamento" as C6
            usecase "Recebe notificação" as C7
            usecase "cancelar reserva" as C9 
            

        }
    
        Cliente -left-> C1
        Cliente --> C2
        Cliente --> C3
        Cliente --> C4 
        Cliente --> C5 
        Cliente --> C6 
        Cliente --> C7 
        Cliente --> C9
        
       
    } 

    package "Processo no Restaurante" as 2C {
            usecase "É direcionado a uma mesa disponível" as C10
            usecase "Escolhe sua refeição" as C12
            usecase "Pede a conta" as C14
        
            Cliente --> C10
            Cliente --> C12 
            Cliente --> C14
        
    }
    

    'casos de uso restaurante
    package "Ações dentro do restaurante" as RT {
        usecase "Direciona o cliente a uma mesa disponível"     as R1
        usecase "Registra o pedido"                             as R3
        usecase "Emite a conta do cliente"                      as R6 


    }

    C10 <--> R1
    C12 <--> R3 
    C14 <--> R6

    Restaurante -up-> RT


    'casos de uso da recepcionista
    
    rectangle "Ações da Recepcionista" as R {
        package "Check-in" as 1R {
            usecase "Recepciona o cliente na chegada"               as UC1
            usecase "Valida os documentos da reserva"               as UC3
            usecase "Realiza o check-in"                            as UC4
            usecase "Instrui sobre funcionamento e comodidades"     as UC7
            usecase "Entrega a chave de acesso ao quarto"           as UC8
        }    
        
        package "Check-out" as 2R {
            usecase "Realiza o check-out"                           as UC10
            usecase "Registar consumo restaurante"                  as UC11
            usecase "Registra pagamento do cliente"                            as UC12 
            usecase "Agradecer pela preferência na hospedagem"      as UC13
        
        
        }
    }

        Recepcionista --> UC1
        Recepcionista --> UC3
        Recepcionista --> UC4
        Recepcionista --> UC7
        Recepcionista --> UC8
        Recepcionista --> UC10
        Recepcionista --> UC11
        Recepcionista --> UC12
        Recepcionista --> UC13

        usecase "Entrega o cartao de acesso do quarto" as UC14
        UC4 ..> UC14 : <<extend>>


    rectangle "Ações do Gerente" as G {
        usecase "Gerar relatorios" as G1   
        usecase "Gerenciar reservas" as G2
        usecase "Interditar quarto" as G3
        usecase "Realocar quarto" as G4

    }

    Gerente --> G1
    Gerente --> G2
    Gerente-->G3
    Gerente-->G4

    usecase "Ocupação, receita, etc" as G5
    usecase "Comunica a equipe de limpeza ou de reforma" as G6

    G1 ..> G5 : <<include>>
    G3 ..> G6 : <<extend>>
    




 
    rectangle "Ações do sistema" as S {
        usecase "Enviar confirmação por email"         as S2
        usecase "Validar dados do cliente"             as S3
        usecase "Gerar número de reserva"              as S4
        usecase "Gerar notificações"                   as S5
        usecase "Calcular valor total da reserva"      as S8

        Sistema --> S2
        Sistema --> S3
        Sistema --> S4
        Sistema --> S5
        Sistema --> S8

    }

    usecase "Enviar confirmação por email" as S9
    usecase "Validar dados do Cliente" as S10
    usecase "Solicita lavanderia, café da manha e garagem" as CL11
    usecase "Calcular valor total da reserva" as CL12


    S5 ..> S9 : <<include>>
    S4 ..> S10 : <<include>>
    C5 ..> CL11 : <<extend>>
    C6 ..> CL12 : <<include>>




    usecase "Realiza o Login" as ex1
    C1 --> ex1 : <<extend>>
    ex1 -left-> C3

    usecase "Escolhe pagar conta como consumo restaurante" as ex2
    C14 --> ex2 : <<extend>>

     
    node " " as ESPACO
    skinparam NodeBorderColor white
    skinparam NodeBackgroundColor white

    
    R-[hidden]->Sistema
    S2-[hidden]->Gerente

    RT-[hidden]-> Restaurante
    Restaurante-[hidden]->Recepcionista
    
    
    ex2 --> UC11





}
@@enduml